export const DEFAULT_CARDS = [
  { id: "1", title: "Elon Musk", organization: "Tesla", column: "sourced" },
  { id: "2", title: "Tim Cook", organization: "Apple", column: "applied" },
  { id: "3", title: "Satya Nadella", organization: "Microsoft", column: "contacted" },
  { id: "4", title: "Sundar Pichai", organization: "Google", column: "hrcall" },
  { id: "5", title: "Jeff Bezos", organization: "Amazon", column: "interview" },
  { id: "6", title: "Mark Zuckerberg", organization: "Meta", column: "sourced" },
  { id: "7", title: "Jensen Huang", organization: "NVIDIA", column: "applied" },
  { id: "8", title: "Susan Wojcicki", organization: "YouTube", column: "contacted" },
  { id: "9", title: "Reed Hastings", organization: "Netflix", column: "hrcall" },
  { id: "10", title: "Brian Chesky", organization: "Airbnb", column: "interview" },
  { id: "11", title: "Jack Dorsey", organization: "Twitter", column: "sourced" },
  { id: "12", title: "Daniel Ek", organization: "Spotify", column: "applied" },
  { id: "13", title: "Evan Spiegel", organization: "Snap Inc.", column: "contacted" },
  { id: "14", title: "Daniel Zhang", organization: "Alibaba", column: "hrcall" },
  { id: "15", title: "Daniel Dines", organization: "UiPath", column: "interview" },
  { id: "16", title: "Brian Armstrong", organization: "Coinbase", column: "sourced" },
  { id: "17", title: "John Foley", organization: "Peloton", column: "applied" },
  { id: "18", title: "Stewart Butterfield", organization: "Slack", column: "contacted" },
  { id: "19", title: "Kevin Systrom", organization: "Instagram", column: "hrcall" },
  { id: "20", title: "Whitney Wolfe Herd", organization: "Bumble", column: "interview" },
];
